pipeline {
  agent none
  stages {
    stage('Back-end - Java') {
      agent { docker { image 'maven:3.8.1-adoptopenjdk-11' } }
      steps {
        // Java "Hello World" in Maven
        sh '''
          mkdir -p src/main/java/com/example
          cat > src/main/java/com/example/App.java << 'EOF'
            package com.example;
            public class App {
              public static void main(String[] args) {
                System.out.println("Hello from Java!");
              }
            }
          EOF
          mvn -q archetype:generate -DgroupId=com.example -DartifactId=hellojava -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
          cd hellojava
          mvn clean compile exec:java -Dexec.mainClass=com.example.App
        '''
      }
    }
    stage('Front-end - Node') {
      agent { docker { image 'node:16-alpine' } }
      steps {
        sh '''
          mkdir hellonode && cd hellonode
          echo 'console.log("Hello from Node!");' > index.js
          node index.js
        '''
      }
    }
  }
}
