pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                script {
                    // Print Maven version
                    sh 'mvn --version'

                    // Create and run HelloWorld.java
                    sh '''
                        echo "public class HelloWorld {
                            public static void main(String[] args) {
                                System.out.println(\\"Hello, World!\\");
                            }
                        }" > HelloWorld.java

                        javac HelloWorld.java
                        java HelloWorld
                    '''
                }
            }
        }
        stage('Front-end') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                script {
                    // Print Node.js version
                    sh 'node --version'
                }
            }
        }
    }
}
